# Generated by Django 4.0.3 on 2022-03-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=200)),
                ('todo_body', models.CharField(max_length=3000)),
                ('completed', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completed_todo', to='api.completed')),
            ],
        ),
    ]
