# Generated by Django 4.0.3 on 2022-03-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_todo_dadjokemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentJokeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present joke', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='NextJokeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next joke', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='dadjokemodel',
            name='completed',
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.DeleteModel(
            name='DadJokeModel',
        ),
    ]
