# Generated by Django 4.0.3 on 2022-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_currentjokemodel_nextjokemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentjokemodel',
            name='present joke',
            field=models.CharField(max_length=10000),
        ),
    ]
