# Generated by Django 4.0.3 on 2022-03-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_currentjokemodel_present joke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentjokemodel',
            old_name='present joke',
            new_name='present_joke',
        ),
        migrations.RenameField(
            model_name='nextjokemodel',
            old_name='next joke',
            new_name='next_joke',
        ),
    ]
